In [2]:
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns

In [8]:
med_exp_data = pd.read_sas("C:/Users/Malcolm/Documents/MedicalExpenditure/data/h216.sas7bdat", format = 'sas7bdat', encoding='iso-8859-1')

In [9]:
med_exp_data.head()

,DUID,PID,DUPERSID,PANEL,FAMID31,FAMID42,FAMID53,FAMID19,FAMIDYR,CPSFAMID,...,RXPTR19,RXOTH19,PERWT19F,FAMWT19F,FAMWT19C,SAQWT19F,VSAQW19F,DIABW19F,VARSTR,VARPSU
0,2320002.0,101.0,2320002101,23.0,B,B,B,B,B,B,...,0.0,0.0,14602.115869,13727.593908,13727.593908,13985.516019,0.0,0.0,2019.0,1.0
1,2320002.0,102.0,2320002102,23.0,A,A,A,A,A,A,...,0.0,0.0,25324.216045,18586.327532,18586.327532,28061.590938,0.0,0.0,2019.0,1.0
2,2320002.0,103.0,2320002103,23.0,A,A,A,A,A,A,...,0.0,0.0,19455.742319,18586.327532,18586.327532,0.000000,0.0,0.0,2019.0,1.0
3,2320005.0,101.0,2320005101,23.0,A,A,A,A,A,A,...,0.0,0.0,5919.292270,6692.229133,6692.229133,0.000000,0.0,0.0,2079.0,1.0
4,2320005.0,102.0,2320005102,23.0,A,A,A,A,A,A,...,7.0,0.0,5356.640305,6692.229133,6692.229133,0.000000,0.0,0.0,2079.0,1.0

In [10]:
med_exp_data.shape

(28512, 1447)

Huge dataset with 1447 columns! We need to make sense of this.